export const routeName = {
  LANDING_SCREEN:"LANDING_SCREEN",
  SPLASH: 'SPLASH',
  LOGIN:'LOGIN',
  BOTTOM_TABS:'BOTTOM_TABS',
  HOME:'HOME',
  REGISTER:'REGISTER',
  ALL_CATEGORY_LIST:'ALL_CATEGORY_LIST',
  CATEGORY_LIST:'CATEGORY_LIST',
  PRODUCT_DETAIL:'PRODUCT_DETAIL',
  SHOPPING_CART:'SHOPPING_CART',
  PAYMENT_METHOD:'PAYMENT_METHOD',
  PROFILE:'PROFILE',
  
};
